[package]
name = "unnamed-desktop-app"
version = "0.1.0"
description = "Unnamed Windows Desktop App"
authors = ["notLimitedRBX"]
edition = "2021"

[build-dependencies]
tauri-build = { version = "2" }

[dependencies]
tauri = { version = "2" }
tauri-plugin-opener = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"

[target.'cfg(windows)'.dependencies]
windows = { version = "0.58", features = ["Win32_Devices_DeviceAndDriverInstallation"] }

[features]
default = ["custom-protocol"]
custom-protocol = ["tauri/custom-protocol"]
